### Endpoint de teste
GET http://localhost:3003/ping

### Endpoint criar novo usuário
POST http://localhost:3003/users/signup
Content-Type: application/json

{
    "name": "criz16",
    "email": "criz16@gmail.com",
    "password": "criz16"
}

### Endpoint logar novo usuário
POST http://localhost:3003/users/login
Content-Type: application/json

{
    "email" :"astrodev@gmail.com",
    "password" : "bananinha"
}

### Endpoint criar novo show
POST http://localhost:3003/shows
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjEwMSIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTY2MDk0NTQxNSwiZXhwIjoxNjYxMDMxODE1fQ.rZ9gRRrPmoAmcRYTvjseSd_PKpO2Y8ysxRgIoKw_q_c
Content-Type: application/json 

{
    "band" : "Detonaltas",
    "starts_id" : "2022-12-25"
}

### Endpoint pegar todos os shows
GET http://localhost:3003/shows 
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjEwMSIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTY2MDg1NzgxNCwiZXhwIjoxNjYwOTQ0MjE0fQ.P6XZEfTORcgy1j2zucngSnZJZznsIUDhsMcQrnJ6ko4

### Endpoint reservar um ticket
POST http://localhost:3003/shows/201
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjEwMSIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTY2MDgzNTA1OCwiZXhwIjoxNjYwOTIxNDU4fQ.Qh0Lvysl4DaeaoZDi-cVlhgnuE3HwIU1Lj4f_HgbCiw

###Endpoint deletar um ticket 
DELETE http://localhost:3003/shows/tickets/201
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjEwMSIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTY2MDg1ODI2MiwiZXhwIjoxNjYwOTQ0NjYyfQ.pmllsTws-18uVY9FE9KVQFnu39zepxUHoO19xgJeSuw