### Ping
GET http://localhost:3003/ping

### Post new Perfume
POST http://localhost:3003/perfumes
Content-Type: application/json

{
    "name": "Ferrari ",
    "brand": "Masculino",
    "price": 250.00,
    "ml": 100
}

### Get list Perfumes
GET http://localhost:3003/perfumes

### Put edit Perfumes
PUT http://localhost:3003/perfumes/03
Content-Type:  application/json

{
    "price": 999
}

### Delete Perfumes
DELETE http://localhost:3003/perfumes/1658251644505